Traceback (most recent call last):
  File "C:\Users\felix\miniconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\felix\miniconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felix\miniconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felix\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\felix\miniconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\felix\miniconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\felix\miniconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Estableciendo un punto inicial para la optimización
initial_guess = [150., 150.]
p = params()

# Optimizando
result = optimize(x -> objective(p,x), initial_guess, BFGS())

# Resultados
optimal_a2, optimal_a3 = Optim.minimizer(result)
optimal_c1 = R * ā + y1 - optimal_a2
optimal_c2 = R * optimal_a2 + y2 - optimal_a3
optimal_c3 = R * optimal_a3 + y3

println("Optimal a2: ", optimal_a2)
println("Optimal a3: ", optimal_a3)
println("Optimal c1: ", optimal_c1)
println("Optimal c2: ", optimal_c2)
println("Optimal c3: ", optimal_c3)

------------------


UndefVarError: `R` not defined

Stacktrace:
 [1] top-level scope
   @ In[3]:10

